Add Azure support

diff --git a/production/packaging/build_and_test_all_in_docker b/production/packaging/build_and_test_all_in_docker
--- a/production/packaging/build_and_test_all_in_docker
+++ b/production/packaging/build_and_test_all_in_docker
@@ -1,5 +1,6 @@
 #!/bin/bash
 # Copyright 2023 Google LLC
+# Copyright (C) Microsoft Corporation. All rights reserved.
 #
 # Licensed under the Apache License, Version 2.0 (the "License");
 # you may not use this file except in compliance with the License.
@@ -50,6 +51,8 @@ declare -i NO_PLATFORM_BUILD=0
 declare -a AMI_REGIONS
 declare GCP_IMAGE_TAG
 declare GCP_IMAGE_REPO
+declare AZURE_IMAGE_TAG
+declare AZURE_IMAGE_REPO
 declare -i GCP_SKIP_IMAGE_UPLOAD=0
 declare -a BUILD_TARGETS=(
   "//tools/secure_invoke/..."
@@ -67,7 +70,7 @@ usage:
     --service-path               [REQUIRED] Recognized values: auction_service, bidding_service, buyer_frontend_service, seller_frontend_service.
                                    Use multiple times to specify more than one service.
     --instance                   [REQUIRED] Recognized values: local, aws
-    --platform                   [REQUIRED] Recognized values: gcp, aws
+    --platform                   [REQUIRED] Recognized values: gcp, aws, azure
     --e2e                        Run e2e mode
     --build-flavor               Recognized values: prod, non_prod, inference_non_prod. Default: prod
                                    Use non_prod to enable verbose logging.
@@ -146,6 +149,14 @@ while [[ $# -gt 0 ]]; do
       ;;
     --gcp-image-repo)
       GCP_IMAGE_REPO="$2"
+      shift 2 || usage
+      ;;
+    --azure-image-tag)
+      AZURE_IMAGE_TAG="$2"
+      shift 2 || usage
+      ;;
+    --azure-image-repo)
+      AZURE_IMAGE_REPO="$2"
       shift 2 || usage
       ;;
     --verbose)
@@ -290,6 +301,21 @@ function build_service_for_gcp() {
   fi
 }
 
+function build_service_for_azure() {
+  declare -r service="$1"
+  # note: use relative path to dist
+  declare -r docker_image=dist/debian/${service}_image.tar
+  if ! [[ -s ${WORKSPACE}/${docker_image} ]]; then
+    printf "Error: docker image tar file not found: %s\n" "${docker_image}" &>/dev/stderr
+    exit 1
+  fi
+  # shellcheck disable=SC2086
+  "${SCRIPT_DIR}"/azure/build_and_test ${VERBOSE_ARG} \
+  --server-image "${docker_image}" \
+  --service-path "${service}" \
+  --azure-image-tag "${AZURE_IMAGE_TAG}" \
+  --azure-image-repo "${AZURE_IMAGE_REPO}"
+}
 function load_service_image() {
   declare -r service="$1"
   declare -r docker_image=dist/debian/${service}_image.tar
@@ -322,6 +348,12 @@ if [[ ${NO_PLATFORM_BUILD} -eq 0 ]]; then
       source  "${SCRIPT_DIR}"/gcp/lib_gcp_artifacts.sh
       for svc in "${SERVICES[@]}"; do
         build_service_for_gcp "${svc}"
+      done
+    ;;
+
+    azure)
+      for svc in "${SERVICES[@]}"; do
+        build_service_for_azure "${svc}"
       done
     ;;
     *)
